### PR TITLE
Update runtime to v0.6.0

### PR DESCRIPTION
**Pull request by aagrawal3**
Update runtime to v0.6.0

### CODE REVIEW

**Comment by briantopping** [comment]
Hi @aagrawal3, I wanted to call out a complexity that these changes introduce and get your opinion. In the previous contract, the code such as [this](https://github.com/kubernetes/cloud-provider-vsphere/blob/master/pkg/nsxt/connector_manager.go#L282) was able to update a password for the connection directly. In the new contract, a new connection must be created if the password changes.

Unfortunately, that's going to be very difficult to support. As you can see [here](https://github.com/kubernetes/cloud-provider-vsphere/blob/55346f5b38ef2cf83a47f50aba07efa49786e889/pkg/cloudprovider/vsphere/cloud.go#L216-L224), the connector is injected as a mutable and [in cloud-provider](https://github.com/kubernetes/cloud-provider/blob/master/plugins.go#L56-L58), the injection fails if the provider already exists.

I started working on a connector proxy that could know if the password had changed and recreate the connector on next use. That's not too bad, but I thought you might want to know about this use case.

**Comment by aagrawal3** [comment]
Hi @briantopping, thank you for your valued feedback. We acknowledge the complexity pointed out by you and looking for the best way to address this. We expect your continued help and support through such feedbacks to make our product better.

**Comment by briantopping** [comment]
Acknowledged and standing by. Happy to help at any time. Sent from my iPhoneOn Apr 7, 2023, at 01:57, Ankit Agrawal ***@***.***> wrote:﻿
Hi @briantopping, thank you for your valued feedback. We acknowledge the complexity pointed out by you and looking for the best way to address this. We expect your continued help and support through such feedbacks to make our product better.

**Comment by aagrawal3** [comment]
Hi @briantopping, we are going to address this in our next release (tentative before end of April.)

**Comment by aagrawal3** [comment]
Hi @briantopping, we introduced a fix in Runtime@0.7.0
https://github.com/vmware/vsphere-automation-sdk-go/pull/23

**Pull request merged**
